/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.poly.UI;

import com.poly.connect.ValueDate;
import com.poly.dao.TaiKhoanDao;
import com.poly.model.TaiKhoan;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Tong Duy Hai
 */
public class LoGin extends javax.swing.JFrame {

    public static String userr;
    public static String name;
    ArrayList<TaiKhoan> ls = new ArrayList<>();

    /**
     * Creates new form LoGin
     */
    public LoGin() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        try {
            File file = new File("‪Connect.txt");
            if (!file.exists()) {
                new KetNoi(this, true).setVisible(true);
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        ChaoJDialog s = new ChaoJDialog(this, true);
        s.setVisible(true);
        try {
            ls = (ArrayList<TaiKhoan>) TaiKhoanDao.getAll();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "error!");
        }
    }

    private boolean checkLoGin(String user, String pass) {
        try {
            if (ValueDate.checkNullDangNhap(user, pass)) {
                int chk = 0;
                for (TaiKhoan nv : ls) {
                    if (nv.getUsername().equals(user) && nv.getPassword().equals(pass) && nv.getRole().equals("hocsinh")) {
                        JOptionPane.showMessageDialog(this, "Xin chào " + nv.getName() + "!");
                        try {
                            name = nv.getName();
                            userr = nv.getUsername();
                            ChonMon chon = new ChonMon();
                            chon.setVisible(true);
                            chk++;
                            dispose();
                        } catch (Exception e) {
                            e.printStackTrace();
                        }

                    } else if (nv.getUsername().equals(user) && nv.getPassword().equals(pass) && nv.getRole().equals("giaovien")) {
                        JOptionPane.showMessageDialog(this, "Xin chào " + nv.getName() + "!");
                        try {
                            name = nv.getName();
                            userr = nv.getUsername();
                            Home chon = new Home();
                            chon.setVisible(true);
                            Home.username = nv.getUsername();
                            Home.pass = nv.getPassword();
                            Home.role = nv.getRole();
                            chk++;
                            dispose();
                        } catch (Exception e) {
                            e.printStackTrace();
                        }

                    } else if (nv.getUsername().equals(user) && nv.getPassword().equals(pass) && nv.getRole().equals("admin")) {
                        JOptionPane.showMessageDialog(this, "Xin chào " + nv.getName() + "!");
                        try {
                            name = nv.getName();
                            userr = nv.getUsername();
                            Home chon = new Home();
                            chon.setVisible(true);
                            Home.username = nv.getUsername();
                            Home.pass = nv.getPassword();
                            Home.role = nv.getRole();
                            chk++;
                            dispose();
                        } catch (Exception e) {
                            e.printStackTrace();
                        }

                    }

                }
                if (chk == 0) {
                    JOptionPane.showMessageDialog(this, "Thông tin không chính xác!");
                    return false;
                }
            }
            return true;
        } catch (Exception e) {
            e.printStackTrace();
            return false;
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnLogin = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        txtPass = new javax.swing.JPasswordField();
        txtUser = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        btnDangNhap = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ÔN THI ĐẠI HỌC KHỐI A");

        pnLogin.setBackground(new java.awt.Color(255, 255, 255));
        pnLogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        pnLogin.setForeground(new java.awt.Color(255, 255, 255));
        pnLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/ICO/icons8_customer_32px_1.png"))); // NOI18N
        pnLogin.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, -1, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/ICO/icons8_Key_32px.png"))); // NOI18N
        pnLogin.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, -1, 40));
        pnLogin.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 250, 30));

        txtPass.setText("jPasswordField1");
        txtPass.setBorder(null);
        txtPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPassFocusGained(evt);
            }
        });
        txtPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPassMouseClicked(evt);
            }
        });
        pnLogin.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 170, 40));

        txtUser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtUser.setText("Nhập username");
        txtUser.setBorder(null);
        txtUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtUserMouseClicked(evt);
            }
        });
        pnLogin.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 170, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/ICO/icons8_User_96px_2.png"))); // NOI18N
        jLabel2.setToolTipText("");
        pnLogin.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, -1, 100));

        jLabel3.setBackground(new java.awt.Color(238, 112, 82));
        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(238, 112, 82));
        jLabel3.setText("USER:");
        pnLogin.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, -1));

        jLabel1.setBackground(new java.awt.Color(238, 112, 82));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(238, 112, 82));
        jLabel1.setText("PASSWORD:");
        pnLogin.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, -1));

        jCheckBox1.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setForeground(new java.awt.Color(238, 112, 82));
        jCheckBox1.setText("Hiện mật khẩu");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        pnLogin.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, -1, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 153, 102));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icon/Delete.png"))); // NOI18N
        jButton1.setText("Thoát");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        pnLogin.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 420, 130, 40));

        btnDangNhap.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnDangNhap.setForeground(new java.awt.Color(255, 153, 102));
        btnDangNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icon/ic_login.png"))); // NOI18N
        btnDangNhap.setText("Đăng Nhập");
        btnDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangNhapActionPerformed(evt);
            }
        });
        pnLogin.add(btnDangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, 130, 40));
        pnLogin.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 250, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 586, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPassFocusGained
        txtPass.setText("");
    }//GEN-LAST:event_txtPassFocusGained

    private void txtPassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPassMouseClicked
        txtPass.setText("");
    }//GEN-LAST:event_txtPassMouseClicked

    private void txtUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUserMouseClicked
        if (txtUser.getText().equals("Nhập username")) {
            txtUser.setText("");
        }
    }//GEN-LAST:event_txtUserMouseClicked

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        if (jCheckBox1.isSelected()) {
            txtPass.setEchoChar((char) 0);
        } else {
            txtPass.setEchoChar('*');
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangNhapActionPerformed
        // TODO add your handling code here:
        if (checkLoGin(txtUser.getText(), txtPass.getText())) {
        }
    }//GEN-LAST:event_btnDangNhapActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoGin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoGin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoGin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoGin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoGin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangNhap;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPanel pnLogin;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
